(function () {
    "use strict";
    angular.module('app').factory('ConstService', [function () {
        return {
            suburbList: ['Alpine (S)',
'Ararat (RC)',
'Ballarat (C)',
'Banyule (C)',
'Bass Coast (S)',
'Baw Baw (S)',
'Bayside (C)',
'Benalla (RC)',
'Boroondara (C)',
'Brimbank (C)',
'Buloke (S)',
'Campaspe (S)',
'Cardinia (S)',
'Casey (C)',
'Central Goldfields (S)',
'Colac-Otway (S)',
'Corangamite (S)',
'Darebin (C)',
'East Gippsland (S)',
'Frankston (C)',
'Gannawarra (S)',
'Glen Eira (C)',
'Glenelg (S)',
'Golden Plains (S)',
'Greater Bendigo (C)',
'Greater Dandenong (C)',
'Greater Geelong (C)',
'Greater Shepparton (C)',
'Hepburn (S)',
'Hindmarsh (S)',
'Hobsons Bay (C)',
'Horsham (RC)',
'Hume (C)',
'Indigo (S)',
'Kingston (C)',
'Knox (C)',
'Latrobe (C)',
'Loddon (S)',
'Macedon Ranges (S)',
'Manningham (C)',
'Mansfield (S)',
'Maribyrnong (C)',
'Maroondah (C)',
'Melbourne (C)',
'Melton (S)',
'Mildura (RC)',
'Mitchell (S)',
'Moira (S)',
'Monash (C)',
'Moonee Valley (C)',
'Moorabool (S)',
'Moreland (C)',
'Mornington Peninsula (S)',
'Mount Alexander (S)',
'Moyne (S)',
'Murrindindi (S)',
'Nillumbik (S)',
'Northern Grampians (S)',
'Port Phillip (C)',
'Pyrenees (S)',
'Queenscliffe (B)',
'South Gippsland (S)',
'Southern Grampians (S)',
'Stonnington (C)',
'Strathbogie (S)',
'Surf Coast (S)',
'Swan Hill (RC)',
'Towong (S)',
'Wangaratta (RC)',
'Warrnambool (C)',
'Wellington (S)',
'West Wimmera (S)',
'Whitehorse (C)',
'Whittlesea (C)',
'Wodonga (RC)',
'Wyndham (C)',
'Yarra (C)',
'Yarra Ranges (S)',
'Yarriambiack (S)',
'Unincorporated Vic',
'No Usual Address (Vic.)'],
            
            countryList: ['Australia',
'Bosnia and Herzegovina',
'Cambodia',
'Canada',
'China (excl. SARs and Taiwan)(b)',
'Croatia',
'Egypt',
'Fiji',
'Former Yugoslav Republic of Macedonia (FYROM)',
'Germany',
'Greece',
'Hong Kong (SAR of China)(b)',
'India',
'Indonesia',
'Iraq',
'Ireland',
'Italy',
'Japan',
'Korea, Republic of (South)',
'Lebanon',
'Malaysia',
'Malta',
'Netherlands',
'New Zealand',
'Philippines',
'Poland',
'Singapore',
'South Africa',
'South Eastern Europe, nfd(c)',
'Sri Lanka',
'Thailand',
'Turkey',
'United Kingdom, Channel Islands and Isle of Man(d)',
'United States of America',
'Vietnam',
'Born elsewhere(e)',
'Country of birth not stated',
'Total'
],
            ageList:[
                'Total all ages',
'0-4 years',
'5-9 years',
'10-14 years ',
'15-19 years ',
'20-24 years',
'25-29 years',
'30-34 years',
'35-39 years',
'40-44 years',
'45-49 years',
'50-54 years',
'55-59 years',
'60-64 years',
'65-69 years',
'70-74 years',
'75-79 years',
'80-84 years',
'85-89 years',
'90-94 years',
'95-99 years',
'100 years and over'

            ],
            
            ancestryList: ['Australian',
'Australian Aboriginal',
'Chinese ',
'Croatian',
'Dutch',
'English',
'Filipino',
'French',
'German',
'Greek',
'Hungarian',
'Indian',
'Irish',
'Italian',
'Korean',
'Lebanese',
'Macedonian',
'Maltese',
'Maori',
'New Zealander',
'Polish',
'Russian',
'Scottish',
'Serbian',
'Sinhalese',
'South African',
'Spanish',
'Turkish',
'Vietnamese',
'Welsh',
'Other(d)',
'Ancestry not stated',
'Total responses(c)',
'Total persons(c)'],
        
            
            languageList: [
'Speaks English only',
'Arabic',
'Assyrian',
'Australian Indigenous Languages ',
'Chinese languages total',
'Cantonese',
'Mandarin',
'Other(b)',
'Croatian',
'Dutch',
'French',
'German',
'Greek',
'Hungarian',
'Indo-Aryan LanguagesTotal',
'Bengali',
'Hindi',
'Punjabi',
'Sinhalese',
'Urdu',
'Other(c)',
'Dari',
'Persian (excluding Dari)',
'Other(d)',
'Iranic Languages total',
'Italian',
'Japanese',
'Khmer',
'Korean',
'Macedonian',
'Maltese',
'Polish',
'Portuguese',
'Russian',
'Samoan',
'Serbian',
'Southeast Asian Austronesian Languages total',
'Filipino ',
'Indonesian',
'Tagalog',
'Other (e)',
'Spanish',
'Tamil',
'Thai',
'Turkish',
'Vietnamese',
'Other(f)',
'Speaks other language total',
'Language spoken at home not stated',
'Total']
        }
    }]);
        
}());